# Project: Android CI Workflow
# name: mart-app CI Workflow

# Settings for when to run the CI workflow
on:
  push:
    branches: [ "master", "dev", "feature/**" ]
  pull_request:
    branches: [ "master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ================= Checkout Repo =================
        uses: actions/checkout@v4

      - name: ================= Set up JDK 17 =================
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: ================= Cache Gradle =================
        uses: gradle/gradle-build-action@v3

      - name: ============== Run Lint + Unit Tests ==============
        run: ./gradlew lint testDebug

      - name: ============== Check CI Success ==============
        run: echo "Done, CI Finished"